version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config_master
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx6g -Xms6g"
      #- bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #ulimits:
      #memlock:
        #soft: -1
        #hard: -1
    volumes:
      - volelasticsearch:/usr/share/elasticsearch/data
    networks:
      - netelasticesearch
    deploy:
      #mode: replicated
      #replicas: 1
      mode: global
      restart_policy:
        condition: on-failure

configs:

  elastic_config_master:
    file: ./elasticsearch/config/elasticsearch.yml


volumes:
  volelasticsearch:
    driver: local

networks:
  netelasticesearch:
    driver: overlay
